fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "change_this_email@gmail.com"
        sender_name: "Despiece team"
    registration:
        confirmation:
            enabled: true