security:
    resource: "security.yml"
    type: be_simple_i18n

profile:
    resource: "profile.yml"
    type: be_simple_i18n
    prefix:
        ca: /ca_profile
        pt: /pt_profile
        en: /profile
        fr: /profil
        es: /perfil

registration:
    resource: "registration.yml"
    type: be_simple_i18n
    prefix:
        ca: /ca_register
        pt: /pt_register
        en: /register
        fr: /registre
        es: /registro

resetting:
    resource: "resetting.yml"
    type: be_simple_i18n
    prefix:
        ca: /ca_resetting
        pt: /pt_resetting
        en: /resetting
        fr: /resetter
        es: /resetear

change_password:
    resource: "change_password.yml"
    type: be_simple_i18n
    prefix:
        ca: /ca_profile
        pt: /pt_profile
        en: /profile
        fr: /profil
        es: /perfil

group:
    resource: "group.yml"
    type: be_simple_i18n
    prefix:
        ca: /ca_group
        pt: /pt_group
        en: /group
        fr: /groupe
        es: /grupo
