#Change Password

fos_user_change_password:
    locales:  { pt: "/pt_change-password", ca: "/ca_change-password", en: "/change-password", fr: "/changer-mot-de-passe", es: "/cambiar-contrasenna" }
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    methods: [GET, POST]