#Group

fos_user_group_list:
    locales:  { ca: "/list", pt: "/list", en: "/list", fr: "/list", es: "/list" }
    defaults: { _controller: FOSUserBundle:Group:list }
    methods: [GET]

fos_user_group_new:
    locales:  { ca: "/new", pt: "/new", en: "/new", fr: "/new", es: "/new" }
    defaults: { _controller: FOSUserBundle:Group:new }
    methods: [GET, POST]

fos_user_group_show:
    locales:  { ca: "/{groupName}", pt: "/{groupName}", en: "/{groupName}", fr: "/{groupName}", es: "/{groupName}" }
    defaults: { _controller: FOSUserBundle:Group:show }
    methods: [GET]

fos_user_group_edit:
    locales:  { ca: "/{groupName}/edit", pt: "/{groupName}/edit", en: "/{groupName}/edit", fr: "/{groupName}/edit", es: "/{groupName}/edit" }
    defaults: { _controller: FOSUserBundle:Group:edit }
    methods: [GET, POST]

fos_user_group_delete:
    locales:  { ca: "/{groupName}/delete", pt: "/{groupName}/delete", en: "/{groupName}/delete", fr: "/{groupName}/delete", es: "/{groupName}/delete" }
    defaults: { _controller: FOSUserBundle:Group:delete }
    methods: [GET]