#Registration

fos_user_registration_register:
    locales:  { ca: "/", pt: "/", en: "/", fr: "/", es: "/" }
    defaults: { _controller: FOSUserBundle:Registration:register }
    methods: [GET, POST]

fos_user_registration_check_email:
    locales:  { ca: "/check-email", pt: "/check-email", en: "/check-email", fr: "/controler-email", es: "/chequear-correo" }
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }
    methods: [GET]

fos_user_registration_confirm:
    locales:  { ca: "/confirm/{token}", pt: "/confirm/{token}", en: "/confirm/{token}", fr: "/confirmer/{token}", es: "/confirmar/{token}" }
    defaults: { _controller: FOSUserBundle:Registration:confirm }
    methods: [GET]

fos_user_registration_confirmed:
    locales:  { ca: "/confirmed", pt: "/confirmed", en: "/confirmed", fr: "/confirme", es: "/confirmado" }
    defaults: { _controller: FOSUserBundle:Registration:confirmed }
    methods: [GET]